### ISSUE TITLE
don't work with unclear traceback message

### ISSUE THREAD

**Issue by AABur** [dannysepler/pytestify#32]
```sh
❯ pytestify git_machete/tests/functional/test_machete.py --show-traceback

Skipping git_machete/tests/functional/test_machete.py because of an issue with pytestify
Traceback (most recent call last):
  File "/Users/aabur/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pytestify/_main.py", line 52, in _fix_path
    contents = rewrite_method_name(
  File "/Users/aabur/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pytestify/fixes/method_name.py", line 43, in rewrite_method_name
    visitor = Visitor(keep_casing=keep_casing).visit_text(contents)
  File "/Users/aabur/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pytestify/_ast_helpers.py", line 22, in visit_text
    self.visit(ast_parse(contents))
  File "/Users/aabur/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pytestify/_ast_helpers.py", line 9, in ast_parse
    return ast.parse(contents)
  File "/Users/aabur/.pyenv/versions/3.9.12/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2068
    assert e.exception.msg == expected_error_message, \  # type: ignore
                                                       ^
SyntaxError: unexpected character after line continuation character
```

**Comment by AABur** [comment]
The problem was incorrect syntax in the source file. Problem solved!

**Comment by dannysepler** [comment]
glad you figured it out!
